# Generated by Django 4.1 on 2022-09-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email_address",
            field=models.EmailField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name="person",
            name="favourite_colour",
            field=models.CharField(
                choices=[("red", "red"), ("blue", "blue")], default="red", max_length=50
            ),
        ),
    ]
