# Generated by Django 4.1 on 2022-08-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community_db", "0002_alter_person_country_alter_person_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"permissions": [("edit_profile", "Can edit a profile")]},
        ),
    ]
