# Generated by Django 4.1 on 2022-08-31 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community_db", "0004_person_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="user",
        ),
        migrations.AddField(
            model_name="person",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
