# Generated by Django 4.1 on 2022-09-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_db", "0005_remove_person_user_person_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="favourite_project",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
